apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
      app   : mysql
      env   : ft_service
      owner : echiles
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi