apiVersion: v1
kind: Service
metadata:
  name: php
  annotations: 
    metallb.universe.tf/allow-shared-ip: metalIP
spec:
  selector:
    app: php
  ports:
    - protocol: TCP
      name: php
      port: 5000
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: php-image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000