apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations: 
    metallb.universe.tf/allow-shared-ip: metalIP
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      name: wordpress
      port: 5050
      targetPort: 5050
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress-image
        imagePullPolicy: Never
        ports:
        - containerPort: 5050