apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations: 
    metallb.universe.tf/allow-shared-ip: metalIP
spec:
  selector:
    app: ftp
  ports:
    - protocol: TCP
      name: ftp
      port: 21
      targetPort: 21
    - protocol: TCP
      name: ftp-passive
      port: 2100
      targetPort: 2100
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftp
  template:
    metadata:
      labels:
        app: ftp
    spec:
      containers:
      - name: ftp
        image: ftp-image
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 2100